### ISSUE TITLE
Server fails to start when used in "proxy" mode

### ISSUE THREAD

**Issue by aaronpowell** [sinedied/ollamazure#3]
I'm looking to use this as a proxy in front of ollama running within a container elsewhere, but it fails because it expects the `ollama` binary to be in `PATH` of the process.

The problem can be traced to `checkOllamaVersion`, which tries to run `ollama --version`, but if you have provided a `ollama-url` command line argument it should bypass that check, assuming that the `fetchApi` passes (like `startOllamaServer` does).

This would mean that you can't get the version number of the ollama server, and thus, can't verify that the ollama server meets the minimum version required, but that's probably an acceptable trade off to have.

**Comment by sinedied** [comment]
Good catch!
I'll fix that when I'm back

**Comment by aaronpowell** [comment]
All good @sinedied, PR #4 is created which fixes this (plus one other issue I found when testing).
